extend type Query {
  documents: [Document!]!
}

type Document {
  id: Cuid!
  title: String!
  content: String!
  createdAt: DateTime!
}

extend type Mutation {
  newDocument(title: String!, content: String!): Document
  deleteDocument(id: Cuid!): Document
}
