extend type Query {
  documents: [Document!]!
}

# type Mutation {
#   newDocument(Name: String!, category: String!, date: DateTime!, type: String!): Document
# }

type Document {
  id: Cuid!
  title: String!
  content: String!
  createdAt: DateTime!
}
