type Article {
  content: String!
  createdAt: DateTime!
  id: Cuid!
  title: String!
}

extend type Query {
  articles: [Article!]!
  findArticle(id: Cuid!): [Article!]!
}

extend type Mutation {
  newArticle(title: String!, content: String!, createdAt: DateTime!): Article
  deleteArticle(id: Cuid!): Article
  updateArticle(title: String!, content: String!, createdAt: DateTime!, id: Cuid!): Article
}
