type Article {
  content: String!
  createdAt: DateTime!
  description: String!
  id: Cuid!
  title: String!
}

extend type Query {
  articles: [Article!]!
  findArticle(id: Cuid!): [Article!]!
}

extend type Mutation {
  newArticle(title: String!, content: String!, createdAt: DateTime!, description: String!): Article
  deleteArticle(id: Cuid!): Article
  updateArticle(title: String!, content: String!, createdAt: DateTime!, id: Cuid!, description: String!): Article
}
