type User {
  id: Cuid!
  firstName: String!
  lastName: String!
  email: String!
  phone: String!
  isAdmin: Boolean
  password: String!
}

extend type Query {
  users: [User!]!
  findUser(id: Cuid!): [User!]!
}

extend type Mutation {
  newUser(
    firstName: String!
    lastName: String!
    email: String!
    phone: String!
    isAdmin: Boolean
    password: String!
  ): User
  deleteUser(id: Cuid!): User
  updateUser(
    firstName: String!
    lastName: String!
    email: String!
    phone: String!
    password: String!
    isAdmin: Boolean
    id: Cuid!
  ): User
}
